export const mockListings = [
  {
    id: "1",
    title: "2022 Kawasaki Ninja ZX-6R",
    price: 11999,
    location: "Los Angeles, CA",
    category: "motorcycles",
    condition: "New",
    imageUrl: "/kawasaki-ninja-motorcycle.png",
    isFeatured: true,
    createdAt: "2023-05-15T14:30:00Z",
    year: 2022,
    mileage: 1250,
    engineSize: "636cc",
  },
  {
    id: "2",
    title: "2021 Harley-Davidson Street Glide",
    price: 24999,
    location: "Chicago, IL",
    category: "motorcycles",
    condition: "Like New",
    imageUrl: "/classic-harley.png",
    isFeatured: true,
    createdAt: "2023-05-14T10:15:00Z",
    year: 2021,
    mileage: 3500,
    engineSize: "1868cc",
  },
  {
    id: "3",
    title: "Shoei RF-1400 Helmet - Medium",
    price: 499,
    location: "New York, NY",
    category: "gear",
    condition: "New",
    imageUrl: "/motorcycle-helmet.png",
    isFeatured: false,
    createdAt: "2023-05-13T16:45:00Z",
  },
  {
    id: "4",
    title: "2020 Ducati Panigale V4",
    price: 21500,
    location: "Miami, FL",
    category: "motorcycles",
    condition: "Excellent",
    imageUrl: "/ducati-panigale.png",
    isFeatured: true,
    createdAt: "2023-05-12T09:20:00Z",
    year: 2020,
    mileage: 5200,
    engineSize: "1103cc",
  },
  {
    id: "5",
    title: "Akrapovič Exhaust System for Yamaha R6",
    price: 899,
    location: "Seattle, WA",
    category: "parts",
    condition: "New",
    imageUrl: "/placeholder.svg?height=600&width=800&query=exhaust system",
    isFeatured: false,
    createdAt: "2023-05-11T13:10:00Z",
  },
  {
    id: "6",
    title: "2019 Honda Gold Wing Tour",
    price: 27999,
    location: "Denver, CO",
    category: "motorcycles",
    condition: "Good",
    imageUrl: "/touring-motorcycle.png",
    isFeatured: true,
    createdAt: "2023-05-10T11:30:00Z",
    year: 2019,
    mileage: 12000,
    engineSize: "1833cc",
  },
  {
    id: "7",
    title: "Motorcycle Lift Stand",
    price: 149,
    location: "Austin, TX",
    category: "tools",
    condition: "Like New",
    imageUrl: "/placeholder.svg?height=600&width=800&query=motorcycle lift",
    isFeatured: false,
    createdAt: "2023-05-09T15:25:00Z",
  },
  {
    id: "8",
    title: "Alpinestars Tech-Air Race Vest",
    price: 699,
    location: "Portland, OR",
    category: "gear",
    condition: "New",
    imageUrl: "/placeholder.svg?height=600&width=800&query=motorcycle airbag vest",
    isFeatured: false,
    createdAt: "2023-05-08T12:40:00Z",
  },
  {
    id: "9",
    title: "2018 Yamaha YZF-R6",
    price: 9500,
    location: "San Diego, CA",
    category: "motorcycles",
    condition: "Good",
    imageUrl: "/yamaha-r6.png",
    isFeatured: true,
    createdAt: "2023-05-07T10:05:00Z",
    year: 2018,
    mileage: 8500,
    engineSize: "599cc",
  },
  {
    id: "10",
    title: "Motorcycle Diagnostic Tool",
    price: 249,
    location: "Phoenix, AZ",
    category: "tools",
    condition: "Excellent",
    imageUrl: "/placeholder.svg?height=600&width=800&query=motorcycle diagnostic tool",
    isFeatured: false,
    createdAt: "2023-05-06T14:15:00Z",
  },
  {
    id: "11",
    title: "2023 Zero SR/F Electric Motorcycle",
    price: 19995,
    location: "San Francisco, CA",
    category: "electric",
    condition: "New",
    imageUrl: "/placeholder.svg?height=600&width=800&query=zero srf electric motorcycle",
    isFeatured: true,
    createdAt: "2023-05-05T09:30:00Z",
    year: 2023,
    mileage: 150,
    engineSize: "Electric",
  },
  {
    id: "12",
    title: "Dainese Racing 4 Leather Suit",
    price: 1299,
    location: "Las Vegas, NV",
    category: "gear",
    condition: "New",
    imageUrl: "/placeholder.svg?height=600&width=800&query=motorcycle leather suit",
    isFeatured: false,
    createdAt: "2023-05-04T16:20:00Z",
  },
  {
    id: "13",
    title: "2021 BMW R 1250 GS Adventure",
    price: 18500,
    location: "Boston, MA",
    category: "motorcycles",
    condition: "Excellent",
    imageUrl: "/placeholder.svg?height=600&width=800&query=bmw gs adventure motorcycle",
    isFeatured: true,
    createdAt: "2023-05-03T11:45:00Z",
    year: 2021,
    mileage: 4200,
    engineSize: "1254cc",
  },
  {
    id: "14",
    title: "Motorcycle Tire Changing Kit",
    price: 89,
    location: "Atlanta, GA",
    category: "tools",
    condition: "New",
    imageUrl: "/placeholder.svg?height=600&width=800&query=motorcycle tire changing kit",
    isFeatured: false,
    createdAt: "2023-05-02T13:55:00Z",
  },
  {
    id: "15",
    title: "2022 Livewire One Electric Motorcycle",
    price: 22799,
    location: "Nashville, TN",
    category: "electric",
    condition: "Like New",
    imageUrl: "/placeholder.svg?height=600&width=800&query=livewire electric motorcycle",
    isFeatured: true,
    createdAt: "2023-05-01T10:25:00Z",
    year: 2022,
    mileage: 800,
    engineSize: "Electric",
  },
  {
    id: "16",
    title: "Yoshimura Exhaust for Suzuki GSXR",
    price: 749,
    location: "Philadelphia, PA",
    category: "parts",
    condition: "New",
    imageUrl: "/placeholder.svg?height=600&width=800&query=motorcycle exhaust",
    isFeatured: false,
    createdAt: "2023-04-30T15:10:00Z",
  },
]
